# Generated by Django 2.2.6 on 2020-02-17 16:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dlogin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'm'), ('female', 'f')], max_length=10)),
                ('date_subscribed', models.DateTimeField(default=datetime.datetime(2020, 2, 17, 21, 40, 26, 195713))),
                ('messages_received', models.IntegerField(default=0)),
            ],
        ),
    ]
