# Generated by Django 3.0.2 on 2020-03-02 09:27

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userLogin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='p_likes',
            field=models.ManyToManyField(related_name='post_like', to='userLogin.dlogin'),
        ),
        migrations.AlterField(
            model_name='dlogin',
            name='date_subscribed',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 2, 14, 57, 38, 746137)),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_author', to='userLogin.dlogin'),
        ),
    ]
