# Generated by Django 3.0.2 on 2020-03-02 09:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userLogin', '0002_auto_20200302_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dlogin',
            name='date_subscribed',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 2, 15, 3, 10, 610279)),
        ),
        migrations.AlterField(
            model_name='post',
            name='p_likes',
            field=models.ManyToManyField(blank=True, related_name='post_like', to='userLogin.dlogin'),
        ),
    ]
