# Generated by Django 3.0.2 on 2020-03-03 07:55

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userLogin', '0007_auto_20200303_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dlogin',
            name='date_subscribed',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 3, 13, 25, 23, 611397)),
        ),
        migrations.RemoveField(
            model_name='post_like',
            name='p_likes',
        ),
        migrations.AddField(
            model_name='post_like',
            name='p_likes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_like', to='userLogin.dlogin'),
        ),
    ]
