# Generated by Django 3.0.2 on 2020-03-03 08:07

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userLogin', '0008_auto_20200303_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='post_like',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_like', to='userLogin.Post'),
        ),
        migrations.AlterField(
            model_name='dlogin',
            name='date_subscribed',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 3, 13, 37, 55, 59524)),
        ),
    ]
