# Generated by Django 3.0.2 on 2020-03-03 08:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userLogin', '0009_auto_20200303_1337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post_like',
            name='p_likes',
        ),
        migrations.AddField(
            model_name='post_like',
            name='post',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='user_like', to='userLogin.Post'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dlogin',
            name='date_subscribed',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 3, 13, 42, 27, 997258)),
        ),
        migrations.AlterField(
            model_name='post_like',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='post_like', to='userLogin.dlogin'),
            preserve_default=False,
        ),
    ]
