# Generated by Django 3.0.2 on 2020-03-05 05:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userLogin', '0013_auto_20200305_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='post_comment',
            name='comment',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='dlogin',
            name='date_subscribed',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 5, 11, 6, 42, 241377)),
        ),
    ]
