# Generated by Django 3.0.2 on 2020-03-05 06:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userLogin', '0016_auto_20200305_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dlogin',
            name='date_subscribed',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 5, 11, 40, 17, 273497)),
        ),
    ]
