# Generated by Django 3.0.2 on 2020-03-05 06:14

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('userLogin', '0017_auto_20200305_1140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post_comment',
            name='comment',
        ),
        migrations.AddField(
            model_name='post_comment',
            name='comments',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dlogin',
            name='date_subscribed',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 5, 11, 43, 23, 6201)),
        ),
    ]
